name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js (Optional if using Node.js for building)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build the site (Optional if you need to build it)
      run: |
        # If you have a build step, add commands here
        # e.g., npm install && npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory to deploy (e.g., ./docs or ./build)
